// <auto-generated />
namespace RGastos.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class funcionazure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(funcionazure));
        
        string IMigrationMetadata.Id
        {
            get { return "201311070712475_funcionazure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
