<?xml version="1.0" encoding="utf-8"?><Database Name="CVisits" Class="CVisitsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\v11.0;Initial Catalog=CVisits;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CVisitsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Visita" Member="Visita">
    <Type Name="Visita">
      <Column Name="VisitaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FechaIngreso" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaPlanificada" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EstadoVisitaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LineaProductoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TipoVisitaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClienteID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>